<?php
$labels = array();
$labels['automaticallycollected']  = 'Diklumpat sacara otomatis';
$labels['useautoabook']  = 'Gunakake buku alamat otomatis';
$labels['useforcompletion'] = 'Gunakake alamat sing diklumpukake kanthi otomatis kanggo autocompletion';
$labels['contactremoved'] = 'Hubungi dihapus saka buku alamat otomatis';
$labels['contactmoved'] = 'Hubungi pindah saka buku alamat otomatis';
?>
